Repository ArkEcosystem/core-tx-tester, pull requests merged in 2019-10, with the labels that each got.

#9 fix: query height from a random seed and set the correct milestone
  index.js
Labels: Complexity: Low, Type: Bugfix

#5 refactor: remove unnecessary loop
  index.js
Labels: Complexity: Low, Type: Refactor

#4 feat: add nodemon and npm scripts
  package.json
Labels: Bounty: Tier 4, Complexity: Low, Type: Feature
