Repository ArkEcosystem/core-tx-tester, pull requests merged in 2019-11, with the labels that each got.

#12 fix: use correct delegateName config option
  index.js
Labels: Complexity: Low, Type: Bugfix

#10 refactor: random transaction count of MultiPayment
  index.js
Labels: Complexity: Low, Type: Refactor

#13 refactor: make next4 compliant
  index.js
Labels: Complexity: Low, Status: Collaborator Approved

#16 refactor: add networkTime to expiration.value only once
  index.js
Labels: Complexity: Low, Status: Collaborator Approved, Type: Refactor
